spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes[0]:
        id: invoice-service
        uri: http://localhost:8002
        predicates:
          - Path=/invoice-service/v1/invoices
        filters:
          - RewritePath=/invoice-service/v1/invoices, /v1/invoices

server:
  port: 8000

management:
  endpoints:
    web:
      exposure:
        include: "*"